version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.keys/secret.key:/keys/private/secret.key
      - ./.keys/public:/keys/public/public.key
